version: '3.8'

services:
  accounts:
    image: service/accounts
    networks:
      - test
    ports:
      - 4001:4001
    environment:
      PORT: 4001
    build:
      context: ./services/accounts
      dockerfile: ../Dockerfile
  inventory:
    image: service/inventory
    networks:
      - test
    ports:
      - 4002:4002
    environment:
      PORT: 4002
    build:
      context: ./services/inventory
      dockerfile: ../Dockerfile
  products:
    image: service/products
    networks:
      - test
    ports:
      - 4003:4003
    environment:
      PORT: 4003
    build:
      context: ./services/products
      dockerfile: ../Dockerfile
  reviews:
    image: service/reviews
    networks:
      - test
    ports:
      - 4004:4004
    environment:
      PORT: 4004
    build:
      context: ./services/reviews
      dockerfile: ../Dockerfile

networks:
  test:
    name: test