version: '3.8'

services:
  gateway:
    image: gateway/mesh
    networks:
      - test
    ports:
      - 4000:4000
    restart: unless-stopped
    environment:
      PORT: 4000
    build:
      context: ./mesh
      dockerfile: ./Dockerfile
    depends_on:
      - accounts
      - inventory
      - products
      - reviews

networks:
  test:
    name: test